EFAppDemo/WebLayer/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebLayer.Models;

namespace WebLayer.Controllers
{
    public class FormController : Controller
    {
        // GET: Form
        public ActionResult Index()
        {
            return View();
        }
		public ActionResult ProcessOne() {
			ViewBag.ProcessedOutput = String.Format("PROCESS ONE: uname={0},upass={1}", Request["userName"], Request["userPass"]);
			return View("Index");

		}
		public ActionResult ProcessTwo(string userName,string userPass) {
			ViewBag.ProcessedOutput = String.Format("PROCESS TWO: uname={0},upass={1}", Request["userName"], Request["userPass"]);
			return View("Index");
		}

		public ActionResult Ajax() {
			return View();
		}
		[HttpPost]
		public ActionResult Calculate(double amount,double rate, int year) {
			double total = (amount * rate * year/100);
			StringBuilder SB = new StringBuilder();
			SB.AppendFormat("<strong>Amount:</strong> {0}\n", amount);
			SB.AppendFormat("<strong>Rate:</strong> {0}\n", rate);
			SB.AppendFormat("<strong>Years:</strong> {0}\n", year);
			SB.AppendFormat("<strong>Total interest:</strong> {0}\n", total);
			ViewBag.FormResults = SB.ToString();
			//return View("Ajax");
			return Content(SB.ToString()); //With AjaxForm

		}
		public ActionResult AjaxModel() {
			CalculationModel model = new CalculationModel();
			model.Amount = 10000;
			model.Rate = 4.2;
			model.Years = 10;
			return View(model);
		}
		//Cross site request Forgery
		[HttpPost]
		[ValidateAntiForgeryToken]//cross site forgery ellenörzés
		public ActionResult CalculateWithModel(CalculationModel model) {
			if(ModelState.IsValid) {
				double total = (model.Amount * model.Rate * model.Years / 100);
				StringBuilder SB = new StringBuilder();
				SB.AppendFormat("<strong>Amount:</strong> {0}\n", model.Amount);
				SB.AppendFormat("<strong>Rate:</strong> {0}\n", model.Rate);
				SB.AppendFormat("<strong>Years:</strong> {0}\n", model.Years);
				SB.AppendFormat("<strong>Total interest:</strong> {0}\n", total);
				ViewBag.FormResults = SB.ToString();
				//return View("Ajax");
				return Content(SB.ToString()); //With AjaxForm
			} else
				return Content("INVALID DATA!");
		}
		
	}
}

EFAppDemo/WebLayer/Views/Form/Ajax.cshtml
@{
    ViewBag.Title = "Ajax";
}

@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
}
<h2>Ajax</h2>
<p>ViewBag: @ViewBag.FormResults</p>
<p id="calculateResults"></p>
@using(Ajax.BeginForm("Calculate", "Form",new AjaxOptions() { UpdateTargetId = "calculateResults" })) {
    <table>
        <tr>
            <td>@Html.Label("Total amount")</td>
            <td>@Html.TextBox("amount")</td>
            
        </tr>
        <tr>
            <td>@Html.Label("Yearly interest rate")</td>
            <td>@Html.TextBox("rate")</td>

        </tr>
        <tr>
            <td>@Html.Label("Number of years")</td>
            <td>@Html.TextBox("year")</td>

        </tr>
        <tr>
            <td><input type="submit" value="SEND" /></td>
        </tr>
    </table>
    
}

EFAppDemo/WebLayer/Views/Form/AjaxModel.cshtml
@model WebLayer.Models.CalculationModel
@{
    ViewBag.Title = "Ajax MODEL";
}

@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
}
<h2>Ajax WITH MODEL</h2>
<p id="calculateResults"></p>
@using(Ajax.BeginForm("CalculateWithModel", "Form",new AjaxOptions() { UpdateTargetId = "calculateResults" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    <div class="editor-label">
        @Html.LabelFor(m => m.Amount)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.Amount)

    </div>
    <div class="editor-label">
        @Html.LabelFor(m => m.Rate)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.Rate)

    </div>
    <div class="editor-label">
        @Html.LabelFor(m => m.Years)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.Years)

    </div>
    <input type="submit" value="SEND" />
    
}

EFAppDemo/WebLayer/Views/Form/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if(IsPost) {
    <p> From ViewBag: @ViewBag.ProcessedOutput</p>
    <p>@Html.ActionLink("Back to the forms","Index")</p>
} else {
    <form method="post" action="/Form/ProcessOne">
        Uname: <input type="email" name="userName" /><br/>
        Upass: <input type="password" name="userPass" />
        <input type="submit" value="SEND P1" />
    </form>
    <hr/>
    <form method="post" action="/Form/ProcessTwo">
        Uname: <input type="email" name="userName" /><br />
        Upass: <input type="password" name="userPass" />
        <input type="submit" value="SEND P2" />
    </form>

}